import {
  DAILY_LOGIN_REWARD,
  STAR_CREATION_REWARD,
  FIRST_STAR_BONUS,
  STREAK_7_BONUS,
  STREAK_30_BONUS,
  INVITE_ACCEPTED_REWARD,
  WEEKLY_BONUS,
  WELCOME_BONUS,
  MAX_STARS_REWARD_PER_DAY,
  MAX_INVITE_REWARDS_PER_DAY,
} from './economy'

describe('economy constants match backend economyRules', () => {
  it.each([
    ['DAILY_LOGIN_REWARD', DAILY_LOGIN_REWARD, 10],
    ['STAR_CREATION_REWARD', STAR_CREATION_REWARD, 5],
    ['FIRST_STAR_BONUS', FIRST_STAR_BONUS, 25],
    ['STREAK_7_BONUS', STREAK_7_BONUS, 50],
    ['STREAK_30_BONUS', STREAK_30_BONUS, 200],
    ['INVITE_ACCEPTED_REWARD', INVITE_ACCEPTED_REWARD, 30],
    ['WEEKLY_BONUS', WEEKLY_BONUS, 20],
    ['WELCOME_BONUS', WELCOME_BONUS, 100],
    ['MAX_STARS_REWARD_PER_DAY', MAX_STARS_REWARD_PER_DAY, 10],
    ['MAX_INVITE_REWARDS_PER_DAY', MAX_INVITE_REWARDS_PER_DAY, 5],
  ] as const)('%s equals %d', (_name, actual, expected) => {
    expect(actual).toBe(expected)
  })
})
