export const DEFAULT_USER_ECONOMY = {
  stardust: 0,
  maxSkies: 2,
  maxMemberships: 20,
  loginStreak: 0,
  previousStreak: 0,
  createdStarsToday: 0,
  lastStarCreationDate: null,
  lastDailyRewardDate: null,
  weeklyBonusWeek: null,
  acceptedInvitesToday: 0,
  lastInviteAcceptDate: null,
  videoProcessedToday: 0,
  lastVideoProcessDate: null,
} as const
